"""
错误代码定义模块

定义所有标准化的错误代码常量，用于程序化错误处理
"""

# ============================================
# 客户端错误 (4xx)
# ============================================

# 验证错误
VALIDATION_ERROR = "VALIDATION_ERROR"
"""输入验证失败"""

INVALID_PARAMETER = "INVALID_PARAMETER"
"""请求参数无效"""

MISSING_PARAMETER = "MISSING_PARAMETER"
"""缺少必需参数"""

# 认证错误
AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
"""认证失败"""

INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
"""用户名或密码错误"""

TOKEN_EXPIRED = "TOKEN_EXPIRED"
"""令牌已过期"""

TOKEN_INVALID = "TOKEN_INVALID"
"""令牌无效"""

# 授权错误
AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
"""授权失败，无权访问"""

INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
"""权限不足"""

# 资源错误
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
"""资源未找到"""

USER_NOT_FOUND = "USER_NOT_FOUND"
"""用户未找到"""

LESSON_NOT_FOUND = "LESSON_NOT_FOUND"
"""课程未找到"""

SUBMISSION_NOT_FOUND = "SUBMISSION_NOT_FOUND"
"""代码提交记录未找到"""

# 冲突错误
CONFLICT_ERROR = "CONFLICT_ERROR"
"""资源冲突"""

RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
"""资源已存在"""

DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
"""重复条目"""

# 速率限制
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
"""请求频率超过限制"""

TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
"""请求过多"""

# ============================================
# 服务端错误 (5xx)
# ============================================

# 通用服务端错误
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
"""服务器内部错误"""

UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
"""意外错误"""

# 沙箱执行错误
SANDBOX_EXECUTION_ERROR = "SANDBOX_EXECUTION_ERROR"
"""代码沙箱执行错误"""

CODE_SAFETY_CHECK_FAILED = "CODE_SAFETY_CHECK_FAILED"
"""代码安全检查失败"""

CODE_TIMEOUT = "CODE_TIMEOUT"
"""代码执行超时"""

CODE_MEMORY_LIMIT_EXCEEDED = "CODE_MEMORY_LIMIT_EXCEEDED"
"""代码执行内存超限"""

# 容器池错误
CONTAINER_POOL_ERROR = "CONTAINER_POOL_ERROR"
"""容器池错误"""

CONTAINER_UNAVAILABLE = "CONTAINER_UNAVAILABLE"
"""无法获取容器"""

CONTAINER_CREATION_FAILED = "CONTAINER_CREATION_FAILED"
"""容器创建失败"""

CONTAINER_UNHEALTHY = "CONTAINER_UNHEALTHY"
"""容器不健康"""

CONTAINER_POOL_EXHAUSTED = "CONTAINER_POOL_EXHAUSTED"
"""容器池耗尽"""

# 数据库错误
DATABASE_ERROR = "DATABASE_ERROR"
"""数据库错误"""

DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
"""数据库连接错误"""

DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR"
"""数据库查询错误"""

DATABASE_TRANSACTION_ERROR = "DATABASE_TRANSACTION_ERROR"
"""数据库事务错误"""

# 外部服务错误
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
"""外部服务错误"""

AI_SERVICE_ERROR = "AI_SERVICE_ERROR"
"""AI 服务错误 (DeepSeek/Claude)"""

AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
"""AI 服务不可用"""

AI_SERVICE_TIMEOUT = "AI_SERVICE_TIMEOUT"
"""AI 服务超时"""

API_CALL_FAILED = "API_CALL_FAILED"
"""API 调用失败"""

# 配置错误
CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
"""配置错误"""

MISSING_CONFIGURATION = "MISSING_CONFIGURATION"
"""缺少配置"""

INVALID_CONFIGURATION = "INVALID_CONFIGURATION"
"""配置无效"""

# 超时错误
TIMEOUT_ERROR = "TIMEOUT_ERROR"
"""操作超时"""

REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
"""请求超时"""

OPERATION_TIMEOUT = "OPERATION_TIMEOUT"
"""操作超时"""

# 服务不可用
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
"""服务不可用"""

MAINTENANCE_MODE = "MAINTENANCE_MODE"
"""维护模式"""

SERVICE_OVERLOADED = "SERVICE_OVERLOADED"
"""服务过载"""

# ============================================
# 错误代码分组 (用于查询和统计)
# ============================================

CLIENT_ERRORS = {
    VALIDATION_ERROR,
    INVALID_PARAMETER,
    MISSING_PARAMETER,
    AUTHENTICATION_ERROR,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    AUTHORIZATION_ERROR,
    INSUFFICIENT_PERMISSIONS,
    RESOURCE_NOT_FOUND,
    USER_NOT_FOUND,
    LESSON_NOT_FOUND,
    SUBMISSION_NOT_FOUND,
    CONFLICT_ERROR,
    RESOURCE_ALREADY_EXISTS,
    DUPLICATE_ENTRY,
    RATE_LIMIT_EXCEEDED,
    TOO_MANY_REQUESTS,
}
"""客户端错误代码集合"""

SERVER_ERRORS = {
    INTERNAL_SERVER_ERROR,
    UNEXPECTED_ERROR,
    SANDBOX_EXECUTION_ERROR,
    CODE_SAFETY_CHECK_FAILED,
    CODE_TIMEOUT,
    CODE_MEMORY_LIMIT_EXCEEDED,
    CONTAINER_POOL_ERROR,
    CONTAINER_UNAVAILABLE,
    CONTAINER_CREATION_FAILED,
    CONTAINER_UNHEALTHY,
    CONTAINER_POOL_EXHAUSTED,
    DATABASE_ERROR,
    DATABASE_CONNECTION_ERROR,
    DATABASE_QUERY_ERROR,
    DATABASE_TRANSACTION_ERROR,
    EXTERNAL_SERVICE_ERROR,
    AI_SERVICE_ERROR,
    AI_SERVICE_UNAVAILABLE,
    AI_SERVICE_TIMEOUT,
    API_CALL_FAILED,
    CONFIGURATION_ERROR,
    MISSING_CONFIGURATION,
    INVALID_CONFIGURATION,
    TIMEOUT_ERROR,
    REQUEST_TIMEOUT,
    OPERATION_TIMEOUT,
    SERVICE_UNAVAILABLE,
    MAINTENANCE_MODE,
    SERVICE_OVERLOADED,
}
"""服务端错误代码集合"""

RETRYABLE_ERRORS = {
    RATE_LIMIT_EXCEEDED,
    TOO_MANY_REQUESTS,
    CONTAINER_UNAVAILABLE,
    CONTAINER_POOL_EXHAUSTED,
    DATABASE_CONNECTION_ERROR,
    AI_SERVICE_UNAVAILABLE,
    AI_SERVICE_TIMEOUT,
    TIMEOUT_ERROR,
    REQUEST_TIMEOUT,
    OPERATION_TIMEOUT,
    SERVICE_UNAVAILABLE,
    SERVICE_OVERLOADED,
}
"""可重试的错误代码集合"""


def is_client_error(error_code: str) -> bool:
    """检查是否为客户端错误"""
    return error_code in CLIENT_ERRORS


def is_server_error(error_code: str) -> bool:
    """检查是否为服务端错误"""
    return error_code in SERVER_ERRORS


def is_retryable_error(error_code: str) -> bool:
    """检查是否为可重试错误"""
    return error_code in RETRYABLE_ERRORS
